version: "3.8"

services:
  web:
    image: josojmf/practicas-i-dev-ci-cd:latest
    container_name: practicas-1-dev-ci-cd
    ports:
      - "5000:5000"
    environment:
      DB_USERNAME: joso
      DB_PASSWORD: test123
      DB_CLUSTER: mongo
      DB_NAME: Practicas_I_Automation_Project
      DB_USERS_COLLECTION: Users
