name: Docker Image Deployment

on:
  workflow_run:
    workflows: ["Docker Image Build and Push"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Log Event Details
      run: |
        echo "Triggered by workflow: ${{ github.event.workflow_run.workflow_id }}"
        echo "Commit SHA: ${{ github.sha }}"

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set Docker image tag
      id: set-tag
      run: |
        echo "Checking if image exists for commit SHA: ${{ github.sha }}"
        if docker pull josojmf/practicas-i-dev-ci-cd:${{ github.sha }}; then
          echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV
        else
          echo "Image for commit ${{ github.sha }} not found, using 'latest' as fallback"
          echo "IMAGE_TAG=latest" >> $GITHUB_ENV
        fi

    - name: Stop and remove existing container
      run: |
        docker stop practicas-i-container || true
        docker rm practicas-i-container || true

    - name: Run the container
      run: |
        echo "Using image tag: ${{ env.IMAGE_TAG }}"
        docker run -d \
          --name practicas-i-container \
          -p 80:80 \
          -e DB_USERNAME=${{ secrets.DB_USERNAME }} \
          -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
          -e DB_CLUSTER=${{ secrets.DB_CLUSTER }} \
          -e DB_NAME=${{ secrets.DB_NAME }} \
          -e DB_USERS_COLLECTION=${{ secrets.DB_USERS_COLLECTION }} \
          -e DB_LOGS_COLLECTION=${{ secrets.DB_LOGS_COLLECTION }} \
          -e DB_SETTINGS_COLLECTION=${{ secrets.DB_SETTINGS_COLLECTION }} \
          -e DB_MESSAGES_COLLECTION=${{ secrets.DB_MESSAGES_COLLECTION }} \
          josojmf/practicas-i-dev-ci-cd:${{ env.IMAGE_TAG }}
