name: Docker Image Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 3: Pull the Docker image from Docker Hub
    - name: Pull Docker image
      run: |
        docker pull josojmf/practicas-i-dev:${{ github.sha }}

    # Step 4: Stop and remove the existing container (if any)
    - name: Stop and remove existing container
      run: |
        docker stop practicas-i-container || true
        docker rm practicas-i-container || true

    # Step 5: Run the container with environment variables
    - name: Run the container
      run: |
        docker run -d \
          --name practicas-i-container \
          -p 80:80 \
          -e DB_USERNAME=${{ secrets.DB_USERNAME }} \
          -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
          -e DB_CLUSTER=${{ secrets.DB_CLUSTER }} \
          -e DB_NAME=${{ secrets.DB_NAME }} \
          -e DB_USERS_COLLECTION=${{ secrets.DB_USERS_COLLECTION }} \
          -e DB_LOGS_COLLECTION=${{ secrets.DB_LOGS_COLLECTION }} \
          -e DB_SETTINGS_COLLECTION=${{ secrets.DB_SETTINGS_COLLECTION }} \
          -e DB_MESSAGES_COLLECTION=${{ secrets.DB_MESSAGES_COLLECTION }} \
          josojmf/practicas-i-dev:${{ github.sha }}
