name: Docker Image Deployment

on:
  workflow_run:
    workflows: ["Docker Image Build and Push"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 3: Trigger the DigitalOcean webhook
    - name: Trigger deployment webhook
      run: |
        curl -X POST http://209.38.255.32:9000/hooks/update-docker-image

    # Step 4: Determine which tag to use
    - name: Set Docker image tag
      id: set-tag
      run: |
        echo "Checking if image exists for commit SHA: ${{ github.sha }}"
        if docker pull josojmf/practicas-i-dev-ci-cd:${{ github.sha }}; then
          echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV
        else
          echo "Image for commit ${{ github.sha }} not found, using 'latest' as fallback"
          echo "IMAGE_TAG=latest" >> $GITHUB_ENV
        fi

    # Step 5: Stop and remove existing container
    - name: Stop and remove existing container
      run: |
        docker stop practicas-i-container || true
        docker rm practicas-i-container || true

    # Step 6: Run the container with the correct image tag
    - name: Run the container
      run: |
        echo "Using image tag: ${{ env.IMAGE_TAG }}"
        docker run -d \
          --name practicas-i-container \
          -p 80:80 \
          -e DB_USERNAME=${{ secrets.DB_USERNAME }} \
          -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
          -e DB_CLUSTER=${{ secrets.DB_CLUSTER }} \
          -e DB_NAME=${{ secrets.DB_NAME }} \
          -e DB_USERS_COLLECTION=${{ secrets.DB_USERS_COLLECTION }} \
          -e DB_LOGS_COLLECTION=${{ secrets.DB_LOGS_COLLECTION }} \
          -e DB_SETTINGS_COLLECTION=${{ secrets.DB_SETTINGS_COLLECTION }} \
          -e DB_MESSAGES_COLLECTION=${{ secrets.DB_MESSAGES_COLLECTION }} \
          josojmf/practicas-i-dev-ci-cd:${{ env.IMAGE_TAG }}
